### ISSUE TITLE
Adding a Cargo.lock

### ISSUE THREAD

**Issue by andir** [eaon/notcoal#1]
I found out about your project yesterday and it looks really promising.

I am a long term `afew` user and looking for a replacement. So far it seems that (with minor adjustments) this project could be a long overdue replacement for me.

When trying to package it for my distribution (NixOS) I figured that there is no `Cargo.lock` file within the release archives nor in the source repository.

Would it be possible to add one to all (new) releases? The idea is that a packaged version of your software would always pull in all the dependencies (in the exact versions) that you deemed working / worthy of a release.

**Comment by eaon** [comment]
For some reason I just saw this now, sorry, I'll include it in the next release!

**Comment by foosinn** [comment]
would love to see this, i stubled over the same issue

**Comment by eaon** [comment]
With quite some delay this is now also in the repository. I'll also cut a new release once https://codeberg.org/eaon/notcoal/issues/7 is resolved.
